apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  annotations:
    traefik.ingress.k8s.io/router.entrypoints: web
spec:
  rules:
    - host: redis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-service
                port:
                  number: 6379