apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-communication-deployment
  labels:
    app: redis-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-communication
  template:
    metadata:
      labels:
        app: redis-communication
    spec:
      containers:
        - name: redis-communication
          image: IMAGE_CORE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            -
              name: REDIS_HOST
              value: "redis-service"
            -
              name: REDIS_PORT
              value: "6379"